### ISSUE TITLE
[feat] 도메인 구현

### ISSUE THREAD

**Issue by minwoo0419** [TEAM-DAWM/SHELLIN-SERVER#6]
## Issue 📌

erd 테이블을 기반으로 도메인을 구현 합니다.

## Todo ✔️

- [ ]  Users 도메인 생성
- [ ] Task 도메인 생성
- [ ] Period 도메인 생성
