### ISSUE TITLE
[refac] 함수 네이밍 수정 및 코드 리팩토링

### ISSUE THREAD

**Issue by minwoo0419** [TEAM-DAWM/SHELLIN-SERVER#77]
## Issue 📌

코드 가독성을 위해서 네이밍 리팩토링 및 코드 리팩토링을 진행합니다.
## Todo ✔️

- [ ]  역할마다 통일성 있는 함수 네이밍 짓기
- [ ] Dto 네이밍 통일
- [ ] 코드 리팩토링
- [ ] AuthWhiteList 범위 수정
