### ISSUE TITLE
[feat] redis 의존성 설치 및 refreshToken 엔티티 생성

### ISSUE THREAD

**Issue by minwoo0419** [TEAM-DAWM/SHELLIN-SERVER#8]
## Issue 📌

redis 환경에서 사용할 refreshToken 엔티티를 생성합니다

## Todo ✔️

- [ ]  redis 의존성 추가
- [ ] refreshToken 엔티티 생성
- [ ] ec2 환경에 redis 설치
